services:
  oracle:
    platform: linux/arm64/v8
    container_name: oracle
    image: rollernaut/oracle19c:latest
    environment:
      - "ORACLE_PWD=system"
    ports:
      - "1521:1521"
    volumes:
      - ./data/oracle/v8data:/opt/oracle/oradata
      - ./scripts:/docker-entrypoint-initdb.d  # 掛載腳本
    networks:
      - my_network  # 讓 Oracle DB 連到自訂的 network

networks:
  my_network:
    external: true  # 這裡使用已經存在的 network