# docker compose -f deploy/docker-compose.yml up     
services:
  policyholders:
    image: policyholders  # 這裡換成你的主程式鏡像名稱
    container_name: policyholders
    restart: always
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    networks:
      - my_network  # 讓應用程式加入相同的 network

networks:
  my_network:
    external: true  # 這裡使用已經存在的 network
