version: '3'
services:
  policyholders:
    image: ${DOCKER_USERNAME}/policyholders  # 使用環境變數來指定鏡像名稱
    container_name: policyholders
    restart: always
    environment:
      - DOCKER_USERNAME=${DOCKER_USERNAME}
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    external: true  # 使用已存在的 external network
