CREATE TABLE policyholders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 保戶編號，Oracle 使用 IDENTITY 自動遞增
    parent_id NUMBER,                                       -- 父節點的 ID
    left_child_id NUMBER,                                   -- 左子節點的 ID
    right_child_id NUMBER,                                  -- 右子節點的 ID
    name VARCHAR2(100) NOT NULL,                            -- 保戶姓名，VARCHAR 改為 VARCHAR2
    registration_date TIMESTAMP,                                 -- 加入日，DATETIME 改為 DATE
    introducer_id NUMBER                                    -- 介紹人保戶編號
);