CREATE TABLE policyholders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 保戶編號
    parent_id NUMBER,                                       -- 父節點的 ID
    left_child_id NUMBER,                                   -- 左子節點的 ID
    right_child_id NUMBER,                                  -- 右子節點的 ID
    name VARCHAR2(100) NOT NULL,                            -- 保戶姓名
    registration_date TIMESTAMP,                            -- 加入日
    introducer_id NUMBER                                    -- 介紹人保戶編號
);

COMMENT ON TABLE policyholders IS '保戶資料';
COMMENT ON COLUMN policyholders.ID IS '保戶編號';
COMMENT ON COLUMN policyholders.PARENT_ID IS '父節點的 ID';
COMMENT ON COLUMN policyholders.LEFT_CHILD_ID IS '左子節點的 ID';
COMMENT ON COLUMN policyholders.RIGHT_CHILD_ID IS '右子節點的 ID';
COMMENT ON COLUMN policyholders.NAME IS '保戶姓名';
COMMENT ON COLUMN policyholders.REGISTRATION_DATE IS '加入日';
COMMENT ON COLUMN policyholders.INTRODUCER_ID IS '介紹人保戶編號';