CREATE TABLE policy (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- 保單編號
    description VARCHAR2(500),                         -- 保單描述
    holder_id NUMBER,                                   -- 保戶id
    premium NUMBER,                                  -- 保費
    create_date TIMESTAMP                          -- 創建日期
);

COMMENT ON TABLE policy IS '保單資料';
COMMENT ON COLUMN policy.ID IS '保單編號';
COMMENT ON COLUMN policy.DESCRIPTION IS '保單描述';
COMMENT ON COLUMN policy.HOLDER_ID IS '保戶id';
COMMENT ON COLUMN policy.PREMIUM IS '保費';
COMMENT ON COLUMN policy.CREATE_DATE IS '創建日期';
