name: Docker Build and Push

on:
  # 可以從 github 上手動觸發 workflow
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: '部署環境'
        required: true
        options:
          - prod
        default: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Enable debug mode
        run: set -x  # 打開 debug 模式，之後的指令都會顯示在 log 中

      - name: Checkout code
        uses: actions/checkout@v4

      # 安裝 Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      # 設置環境變數
      - name: Write deploy .env
        run: echo "${{ secrets.DOT_ENV }}" > ./deploy/.env

      - name: Run deploy.sh
        run: |
            chmod +x ./deploy/remote/deploy.sh
            ./deploy/remote/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          SSH_USER: ${{ secrets.GCP_SSH_USER }}
          SSH_HOST: ${{ secrets.GCP_SSH_HOST }}

