name: Docker Build and Push

on:
  push:
    branches:
      - 06-deploy  # 設定觸發條件

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable debug mode
        run: set -x  # 打開 debug 模式，之後的指令都會顯示在 log 中

      # 設置 Docker 環境變數
      - name: Set up Docker environment
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV

      # 安裝 Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run docker-build.sh
        run: |
          # chmod +x ./deploy/docker-build.sh
          # ./deploy/docker-build.sh
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}

      - name: Run deploy.sh
        run: |
            chmod +x ./deploy/deploy.sh
            ./deploy/deploy.sh
        env:
          SSH_USER: ${{ secrets.GCP_SSH_USER }}
          SSH_HOST: ${{ secrets.GCP_SSH_HOST }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

